"""Curated starter catalog shown on a fresh LibSys installation."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class CatalogBook:
    title: str
    author: str
    isbn: str
    category: str
    year: int
    summary: str
    copies: int = 4

    @property
    def cover_url(self) -> str:
        return f"https://covers.openlibrary.org/b/isbn/{self.isbn}-L.jpg?default=false"


DEFAULT_CATALOG: tuple[CatalogBook, ...] = (
    CatalogBook(
        "1984",
        "George Orwell",
        "9780451524935",
        "Bilim Kurgu",
        1949,
        "Winston Smith, her hareketin izlendiği Okyanusya'da geçmişi iktidarın istediği biçimde yeniden yazar. Yasak bir yakınlık ve hakikat arayışı, onu Büyük Birader'in baskıcı düzeniyle yüzleşmeye zorlar.",
    ),
    CatalogBook(
        "Cesur Yeni Dünya",
        "Aldous Huxley",
        "9780060850524",
        "Bilim Kurgu",
        1932,
        "İnsanların daha doğmadan sınıflara ayrıldığı, mutluluğun haz ve tüketimle üretildiği kusursuz görünen bir gelecek. Sistemin dışından gelen John, özgür irade ile konfor arasındaki bedeli sorgular.",
    ),
    CatalogBook(
        "Fahrenheit 451",
        "Ray Bradbury",
        "9781451673319",
        "Bilim Kurgu",
        1953,
        "Kitapların yasaklandığı bir toplumda itfaiyeci Guy Montag'ın görevi onları yakmaktır. Merak ettiği tek bir sayfa, ezberlediği hayatı ve sessizce itaat eden dünyayı değiştirmeye başlar.",
    ),
    CatalogBook(
        "Dune",
        "Frank Herbert",
        "9780441172719",
        "Bilim Kurgu",
        1965,
        "Paul Atreides, evrendeki en değerli madde olan baharatın tek kaynağı Arrakis'e gelir. Çölün ekolojisi, hanedan entrikaları ve kehanetler arasında kendi gücünün sonuçlarıyla tanışır.",
    ),
    CatalogBook(
        "Vakıf",
        "Isaac Asimov",
        "9780553293357",
        "Bilim Kurgu",
        1951,
        "Hari Seldon matematiksel psikotarih bilimiyle Galaktik İmparatorluk'un çöküşünü öngörür. İnsanlığın karanlık çağını kısaltmak için bilginlerden oluşan küçük bir Vakıf kurar.",
    ),
    CatalogBook(
        "Neuromancer",
        "William Gibson",
        "9780441569595",
        "Bilim Kurgu",
        1984,
        "Yeteneklerini kaybetmiş bilgisayar korsanı Case, tehlikeli bir yapay zekâ görevi için yeniden siberuzaya bağlanır. Neon şehirlerden dijital bilinçlere uzanan yolculuk siberpunk türünün temel taşlarından biridir.",
    ),
    CatalogBook(
        "Karanlığın Sol Eli",
        "Ursula K. Le Guin",
        "9780441478125",
        "Bilim Kurgu",
        1969,
        "Elçi Genly Ai, sabit cinsiyetin bulunmadığı kış gezegeni Gethen'i gezegenler birliğine katmaya çalışır. Siyasi güvensizlik içinde kurulan beklenmedik dostluk, kimlik ve bağlılık kavramlarını dönüştürür.",
    ),
    CatalogBook(
        "Mülksüzler",
        "Ursula K. Le Guin",
        "9780061054884",
        "Bilim Kurgu",
        1974,
        "Fizikçi Shevek, anarşist Anarres ile zengin Urras arasındaki duvarı aşarak bilimsel fikrini paylaşmak ister. İki toplumun kusurları üzerinden özgürlük, mülkiyet ve aidiyet sorgulanır.",
    ),
    CatalogBook(
        "Otostopçunun Galaksi Rehberi",
        "Douglas Adams",
        "9780345391803",
        "Bilim Kurgu",
        1979,
        "Dünya beklenmedik biçimde yok edilmeden saniyeler önce Arthur Dent bir uzay gemisine alınır. Yanında bir havlu ve tuhaf bir rehberle evrenin bürokrasisi içinde son derece komik bir yolculuğa çıkar.",
    ),
    CatalogBook(
        "Marslı",
        "Andy Weir",
        "9780553418026",
        "Bilim Kurgu",
        2011,
        "Astronot Mark Watney bir kaza sonrası Mars'ta tek başına kalır. Sınırlı erzak, bilimsel yaratıcılık ve inatçı mizahıyla hayatta kalmanın ve Dünya'ya sesini duyurmanın yolunu arar.",
    ),
    CatalogBook(
        "Hobbit",
        "J.R.R. Tolkien",
        "9780547928227",
        "Fantastik",
        1937,
        "Konforuna düşkün Bilbo Baggins, on üç cüce ve büyücü Gandalf'la kayıp bir krallığı geri almak üzere yola çıkar. Yolculuk onu troller, bilmeceler ve ejderha Smaug'la karşılaştırır.",
    ),
    CatalogBook(
        "Yüzüklerin Efendisi: Yüzük Kardeşliği",
        "J.R.R. Tolkien",
        "9780547928210",
        "Fantastik",
        1954,
        "Frodo, karanlık hükümdarın Tek Yüzük'ünü yok etmek için Shire'dan ayrılır. Farklı halklardan dokuz yolcunun kurduğu kardeşlik, Orta Dünya'nın kaderini taşıyan zorlu bir göreve başlar.",
    ),
    CatalogBook(
        "Harry Potter ve Felsefe Taşı",
        "J.K. Rowling",
        "9780590353427",
        "Fantastik",
        1997,
        "Harry on birinci yaş gününde bir büyücü olduğunu ve Hogwarts'a kabul edildiğini öğrenir. Yeni dostluklarının arasında okulun koridorlarında saklanan eski bir sırrın izini sürer.",
    ),
    CatalogBook(
        "Rüzgârın Adı",
        "Patrick Rothfuss",
        "9780756404741",
        "Fantastik",
        2007,
        "Efsanevi müzisyen ve büyücü Kvothe, kimliğini gizlediği bir handa hayat hikâyesini anlatmaya başlar. Çocukluğundan Üniversite'ye uzanan anlatı, zekâ, müzik ve kayıp bir ailenin gizemiyle örülür.",
    ),
    CatalogBook(
        "Yerdeniz Büyücüsü",
        "Ursula K. Le Guin",
        "9780547773742",
        "Fantastik",
        1968,
        "Genç Ged, gücünü kanıtlama hırsıyla dünyaya karanlık bir gölge salar. Yerdeniz adalarında onu izleyen bu varlıkla yüzleşirken büyünün denge ve sorumluluk istediğini öğrenir.",
    ),
    CatalogBook(
        "Aslan, Cadı ve Dolap",
        "C.S. Lewis",
        "9780064471046",
        "Fantastik",
        1950,
        "Dört kardeş eski bir dolaptan sonsuz kışın hüküm sürdüğü Narnia'ya geçer. Aslan'ın dönüşüyle Beyaz Cadı'ya karşı cesaret, sadakat ve fedakârlık sınavı başlar.",
    ),
    CatalogBook(
        "Taht Oyunları",
        "George R.R. Martin",
        "9780553593716",
        "Fantastik",
        1996,
        "Westeros'un soylu aileleri Demir Taht için ittifaklar kurup ihanetler planlar. Kuzeyde ise unutulduğu sanılan daha eski bir tehlike yaklaşmaktadır.",
    ),
    CatalogBook(
        "Son İmparatorluk",
        "Brandon Sanderson",
        "9780765350381",
        "Fantastik",
        2006,
        "Küllerin yağdığı ve karanlık hükümdarın bin yıldır hüküm sürdüğü dünyada hırsız Vin gizli gücünü keşfeder. Bir grup asiyle imkânsız görünen imparatorluk soygununa katılır.",
    ),
    CatalogBook(
        "Gurur ve Önyargı",
        "Jane Austen",
        "9780141439518",
        "Klasik",
        1813,
        "Elizabeth Bennet ile mesafeli Bay Darcy'nin ilk izlenimleri gurur ve yanlış anlamalarla biçimlenir. Zekâ dolu anlatı aşkın yanında sınıf, aile ve bağımsızlık üzerine de keskin bir bakış sunar.",
    ),
    CatalogBook(
        "Suç ve Ceza",
        "Fyodor Dostoyevski",
        "9780143058144",
        "Klasik",
        1866,
        "Yoksul öğrenci Raskolnikov, sıra dışı insanların ahlakın üzerinde olabileceği düşüncesini korkunç bir suçla sınar. Vicdanı ve çevresindeki insanlar onu adalet ile kefaret arasında sıkıştırır.",
    ),
    CatalogBook(
        "Sefiller",
        "Victor Hugo",
        "9780451419439",
        "Klasik",
        1862,
        "Jean Valjean küçük bir suçun gölgesinden kurtulup iyi bir hayat kurmaya çalışırken müfettiş Javert onu izler. Roman merhamet, adalet ve toplumsal eşitsizliği geniş bir insanlık panoramasıyla anlatır.",
    ),
    CatalogBook(
        "Bülbülü Öldürmek",
        "Harper Lee",
        "9780061120084",
        "Klasik",
        1960,
        "Scout Finch, küçük bir Güney kasabasında büyürken avukat babasının haksız yere suçlanan siyah bir adamı savunmasına tanık olur. Çocuk bakışı önyargı, cesaret ve empatiyi görünür kılar.",
    ),
    CatalogBook(
        "Don Kişot",
        "Miguel de Cervantes",
        "9780060934347",
        "Klasik",
        1605,
        "Şövalye romanslarını fazlasıyla ciddiye alan Alonso Quijano, Don Kişot adıyla adalet dağıtmak üzere yola çıkar. Sancho Panza ile maceraları hayal ile gerçek arasındaki sınırı mizahla sorgular.",
    ),
    CatalogBook(
        "Muhteşem Gatsby",
        "F. Scott Fitzgerald",
        "9780743273565",
        "Klasik",
        1925,
        "Gizemli milyoner Jay Gatsby görkemli partilerinin ardında geçmişte kalan bir aşka ulaşmaya çalışır. Caz Çağı'nın parıltısı altında Amerikan Rüyası'nın kırılganlığı ortaya çıkar.",
    ),
    CatalogBook(
        "Jane Eyre",
        "Charlotte Brontë",
        "9780141441146",
        "Klasik",
        1847,
        "Zorlu bir çocukluktan gelen Jane, Thornfield malikânesinde mürebbiye olur ve evin sahibi Rochester'a yakınlaşır. Ancak evin sakladığı sır, sevgisiyle özsaygısı arasında seçim yapmasına yol açar.",
    ),
    CatalogBook(
        "Uğultulu Tepeler",
        "Emily Brontë",
        "9780141439556",
        "Klasik",
        1847,
        "Heathcliff ile Catherine'in tutkulu ve yıkıcı bağı iki ailenin kuşaklarına yayılır. Yorkshire kırlarının sert atmosferi içinde aşk, intikam ve sınıf çatışması iç içe geçer.",
    ),
    CatalogBook(
        "Savaş ve Barış",
        "Lev Tolstoy",
        "9781400079988",
        "Klasik",
        1869,
        "Napolyon savaşları sırasında Rus aristokrasisinden ailelerin hayatları tarihsel dönüşümle kesişir. Tolstoy savaşın büyük anlatısını sevgi, kayıp ve anlam arayışının mahrem anlarıyla birleştirir.",
    ),
    CatalogBook(
        "Anna Karenina",
        "Lev Tolstoy",
        "9780143035008",
        "Klasik",
        1877,
        "Anna'nın Vronski ile ilişkisi onu toplumun katı beklentileriyle karşı karşıya getirir. Paralel hayatlar üzerinden aşk, aile, kıskançlık ve değişen Rusya incelenir.",
    ),
    CatalogBook(
        "Karamazov Kardeşler",
        "Fyodor Dostoyevski",
        "9780374528379",
        "Klasik",
        1880,
        "Bir babanın ölümü etrafında farklı karakterlere sahip üç kardeş şüphe altında kalır. İnanç, özgür irade, suç ve sorumluluk üzerine derin bir aile dramı gelişir.",
    ),
    CatalogBook(
        "Küçük Prens",
        "Antoine de Saint-Exupéry",
        "9780156012195",
        "Roman",
        1943,
        "Çöle düşen bir pilot, küçük asteroidinden gezegenleri dolaşarak gelen Küçük Prens'le tanışır. Onun sade soruları dostluk, sevgi ve yetişkinlerin unuttuğu değerleri yeniden görünür kılar.",
    ),
    CatalogBook(
        "Simyacı",
        "Paulo Coelho",
        "9780061122415",
        "Roman",
        1988,
        "Endülüslü çoban Santiago tekrar eden rüyasının peşinden Mısır piramitlerine gider. Yol boyunca kendi kişisel menkıbesini dinlemeyi ve aradığı hazinenin anlamını öğrenir.",
    ),
    CatalogBook(
        "Uçurtma Avcısı",
        "Khaled Hosseini",
        "9781594631931",
        "Roman",
        2003,
        "Amir ile Hassan'ın Kabil'deki çocukluk dostluğu bir ihanetle kırılır. Yıllar sonra gelen bir haber Amir'e geçmişiyle yüzleşme ve kefaret arama fırsatı verir.",
    ),
    CatalogBook(
        "Dönüşüm",
        "Franz Kafka",
        "9780553213690",
        "Roman",
        1915,
        "Gregor Samsa bir sabah dev bir böceğe dönüşmüş olarak uyanır. Ailesinin değişen tavrı, insan değerinin üretkenlik ve kabul üzerinden nasıl ölçüldüğünü çarpıcı biçimde gösterir.",
    ),
    CatalogBook(
        "Fareler ve İnsanlar",
        "John Steinbeck",
        "9780140177398",
        "Roman",
        1937,
        "Gezici işçiler George ile Lennie kendilerine ait küçük bir çiftlik kurma hayali taşır. Büyük Buhran'ın sert koşulları, dostluklarını ve kırılgan umutlarını sınar.",
    ),
    CatalogBook(
        "Sapiens",
        "Yuval Noah Harari",
        "9780062316097",
        "Tarih",
        2011,
        "Homo sapiens'in küçük topluluklardan küresel uygarlığa uzanan yolculuğu bilişsel, tarımsal ve bilimsel devrimlerle ele alınır. Para, din ve devlet gibi ortak kurguların işbirliğini nasıl mümkün kıldığı tartışılır.",
    ),
    CatalogBook(
        "Homo Deus",
        "Yuval Noah Harari",
        "9780062464316",
        "Tarih",
        2015,
        "İnsanlık açlık, salgın ve savaşla mücadelesinde ilerlerken yeni hedeflerini ölümsüzlük, mutluluk ve tanrısal güç olarak belirliyor. Biyoteknoloji ile algoritmaların gelecekteki etkileri sorgulanıyor.",
    ),
    CatalogBook(
        "Tüfek, Mikrop ve Çelik",
        "Jared Diamond",
        "9780393354324",
        "Tarih",
        1997,
        "Toplumların farklı hızlarda gelişmesini biyolojik üstünlük yerine coğrafya, evcilleştirilebilir türler ve hastalıklarla açıklar. Kıtalar arasındaki eşitsizliğin uzun tarihine bütüncül bir yaklaşım sunar.",
    ),
    CatalogBook(
        "İnsanın Anlam Arayışı",
        "Viktor E. Frankl",
        "9780807014295",
        "Psikoloji",
        1946,
        "Frankl toplama kamplarındaki deneyimlerini insanın en ağır koşullarda bile anlam bulabilme gücüyle birleştirir. Logoterapi yaklaşımı, yaşamın bizden ne beklediğine odaklanır.",
    ),
    CatalogBook(
        "Kendime Düşünceler",
        "Marcus Aurelius",
        "9780140449334",
        "Felsefe",
        180,
        "Roma İmparatoru Marcus Aurelius'un kendisi için tuttuğu notlar, gücün ortasında erdemli ve ölçülü kalma çabasını gösterir. Stoacı düşünce günlük kaygılara sade ve dirençli bir bakış getirir.",
    ),
    CatalogBook(
        "Devlet",
        "Platon",
        "9780140455113",
        "Felsefe",
        -375,
        "Sokrates ve arkadaşları adaletin bireyde ve toplumda ne anlama geldiğini tartışır. İdeal devlet, eğitim, yönetim ve mağara alegorisi üzerinden bilginin sorumluluğu araştırılır.",
    ),
    CatalogBook(
        "Böyle Buyurdu Zerdüşt",
        "Friedrich Nietzsche",
        "9780140441185",
        "Felsefe",
        1883,
        "Zerdüşt yıllar süren yalnızlığından dönerek insana kendi değerlerini yaratma çağrısı yapar. Şiirsel anlatı üstinsan, bengi dönüş ve geleneksel ahlakın aşılması fikirlerini işler.",
    ),
    CatalogBook(
        "Yabancı",
        "Albert Camus",
        "9780679720201",
        "Felsefe",
        1942,
        "Meursault, annesinin ölümünden sonra toplumun beklediği duyguları göstermeden yaşamına devam eder. İşlediği suçtan çok kayıtsızlığı yargılanırken hayatın absürtlüğü belirginleşir.",
    ),
    CatalogBook(
        "Doğu Ekspresinde Cinayet",
        "Agatha Christie",
        "9780062693662",
        "Polisiye",
        1934,
        "Lüks tren kar fırtınasıyla durduğunda bir yolcu kilitli kompartımanında ölü bulunur. Hercule Poirot, birbirinden farklı yolcuların ifadelerindeki ortak geçmişi çözmeye çalışır.",
    ),
    CatalogBook(
        "On Kişiydiler",
        "Agatha Christie",
        "9780062073488",
        "Polisiye",
        1939,
        "Birbirini tanımayan on kişi ıssız bir adadaki konağa davet edilir. Geçmiş suçlarını açıklayan bir kayıt çaldığında, adadan kaçışın olmadığı ölümcül bir hesaplaşma başlar.",
    ),
    CatalogBook(
        "Da Vinci Şifresi",
        "Dan Brown",
        "9780307474278",
        "Polisiye",
        2003,
        "Louvre'daki bir cinayetin ardında bırakılan semboller Robert Langdon ile Sophie Neveu'yü tarihsel bir sırrın peşine düşürür. Paris'ten Londra'ya uzanan yarışta sanat, inanç ve komplolar iç içe geçer.",
    ),
    CatalogBook(
        "Atomik Alışkanlıklar",
        "James Clear",
        "9780735211292",
        "Kişisel Gelişim",
        2018,
        "Kalıcı değişimin büyük hedeflerden çok her gün tekrarlanan küçük sistemlerle oluştuğunu savunur. İyi alışkanlıkları görünür ve kolay, kötü alışkanlıkları zor hâle getiren uygulanabilir bir çerçeve sunar.",
    ),
    CatalogBook(
        "Hızlı ve Yavaş Düşünme",
        "Daniel Kahneman",
        "9780374533557",
        "Psikoloji",
        2011,
        "Zihnin hızlı, sezgisel sistemiyle yavaş ve analitik sistemi arasındaki etkileşimi açıklar. Kararlarımızı etkileyen bilişsel yanılgılar deneyler ve gündelik örneklerle görünür kılınır.",
    ),
    CatalogBook(
        "Etkili İnsanların 7 Alışkanlığı",
        "Stephen R. Covey",
        "9781982137274",
        "Kişisel Gelişim",
        1989,
        "Kişisel ve profesyonel etkinliği geçici teknikler yerine karakter ilkeleri üzerine kurar. Proaktif olmaktan sinerji yaratmaya uzanan yedi alışkanlık, sürdürülebilir gelişim için bütünlüklü bir yol sunar.",
    ),
    CatalogBook(
        "Hayvan Çiftliği",
        "George Orwell",
        "9780451526342",
        "Klasik",
        1945,
        "Bir çiftliğin hayvanları eşit ve özgür bir düzen kurmak için insan sahiplerine başkaldırır. Ancak iktidarı ele geçiren domuzlar devrimin ilkelerini yavaşça değiştirirken eşitlik vaadi yeni bir baskı biçimine dönüşür.",
    ),
    CatalogBook(
        "Ender'in Oyunu",
        "Orson Scott Card",
        "9780812550702",
        "Bilim Kurgu",
        1985,
        "Çocuk dâhi Ender Wiggin, insanlığı yaklaşan uzaylı saldırısından korumak için acımasız bir savaş okulunda eğitilir. Strateji oyunları ile gerçek çatışma arasındaki sınır silinirken zaferin ahlaki bedeliyle yüzleşir.",
    ),
    CatalogBook(
        "Snow Crash",
        "Neal Stephenson",
        "9780553380958",
        "Bilim Kurgu",
        1992,
        "Hiro Protagonist gündüzleri pizza dağıtır, geceleri ise Metaverse'de usta bir kılıç savaşçısıdır. Dijital dünyayı ve insan dilini tehdit eden Snow Crash virüsünün kökenini araştırırken teknoloji ile mitoloji iç içe geçer.",
    ),
    CatalogBook(
        "Mars Yıllıkları",
        "Ray Bradbury",
        "9781451678192",
        "Bilim Kurgu",
        1950,
        "İnsanlığın Mars'a yaptığı seferleri ve gezegende kurduğu kırılgan yerleşimleri birbirine bağlı öykülerle anlatır. Dünyalıların umutları, önyargıları ve yıkıcı alışkanlıkları yeni gezegende şiirsel bir aynaya dönüşür.",
    ),
    CatalogBook(
        "Damızlık Kızın Öyküsü",
        "Margaret Atwood",
        "9780385490818",
        "Distopya",
        1985,
        "Doğurganlığın azaldığı Gilead rejiminde kadınlar katı sınıflara ayrılır ve bedenleri devlet tarafından denetlenir. Offred, geçmiş yaşamının anılarıyla ayakta kalırken özgürlük için sessiz direniş yolları arar.",
    ),
    CatalogBook(
        "Beni Asla Bırakma",
        "Kazuo Ishiguro",
        "9781400078776",
        "Roman",
        2005,
        "Kathy, Ruth ve Tommy görünüşte huzurlu bir yatılı okulda birlikte büyür. Yıllar sonra yetiştiriliş amaçlarının karanlık gerçeğini kavradıklarında dostluk, aşk, hafıza ve insan olmanın anlamı üzerine düşünmek zorunda kalırlar.",
    ),
    CatalogBook(
        "Yol",
        "Cormac McCarthy",
        "9780307387899",
        "Roman",
        2006,
        "Bir baba ile oğlu, felaket sonrası küle dönmüş Amerika'da güneye doğru yürür. Açlık ve şiddetle çevrili yolculuklarında birbirlerine duydukları sevgi, insanlığın son ışığını koruyan tek sığınakları olur.",
    ),
    CatalogBook(
        "Dracula",
        "Bram Stoker",
        "9780141439846",
        "Gotik",
        1897,
        "Genç avukat Jonathan Harker, gizemli Kont Dracula'nın Transilvanya'daki şatosuna gider. Kont İngiltere'ye ulaştığında bir grup dost, Mina'yı kurtarmak ve kadim kötülüğün yayılmasını durdurmak için güçlerini birleştirir.",
    ),
    CatalogBook(
        "Frankenstein",
        "Mary Shelley",
        "9780141439471",
        "Gotik",
        1818,
        "Bilim insanı Victor Frankenstein cansız maddeden bir varlık yaratır, fakat sonucundan dehşete düşerek onu terk eder. Sevgi ve kabul görmeyen yaratık öfkeye sürüklenirken sorumluluk ile insanlık arasındaki sınırlar sorgulanır.",
    ),
    CatalogBook(
        "Dorian Gray'in Portresi",
        "Oscar Wilde",
        "9780141439570",
        "Klasik",
        1890,
        "Genç Dorian Gray güzelliğinin hiç solmamasını, yaşlanmanın izlerini portresinin taşımasını diler. Dileği gerçekleşince haz ve çıkar peşinde sınır tanımaz; saklı tablo ise vicdanının giderek kararan kaydına dönüşür.",
    ),
    CatalogBook(
        "Monte Cristo Kontu",
        "Alexandre Dumas",
        "9780140449266",
        "Macera",
        1844,
        "Edmond Dantès işlemediği bir suç yüzünden hapsedilir ve hayatı elinden alınır. Hapisten kaçıp büyük bir servete kavuştuğunda Monte Cristo Kontu kimliğiyle kendisine ihanet edenlerden incelikle hesap sormaya başlar.",
    ),
    CatalogBook(
        "İki Şehrin Hikâyesi",
        "Charles Dickens",
        "9780141439600",
        "Tarihî Roman",
        1859,
        "Fransız Devrimi'nin arifesinde Londra ile Paris arasında kesişen hayatları anlatır. Aşk, fedakârlık ve yeniden doğuş temaları, toplumsal öfkenin şiddete dönüştüğü çalkantılı bir tarihsel fonda gelişir.",
    ),
    CatalogBook(
        "Büyük Umutlar",
        "Charles Dickens",
        "9780141439563",
        "Klasik",
        1861,
        "Yetim Pip, gizemli bir hayırsever sayesinde beyefendi olma fırsatı bulur ve Londra'ya gider. Sınıf atlama arzusu onu köklerinden uzaklaştırırken sadakat, utanç ve gerçek değerin ne olduğu üzerine zorlu dersler alır.",
    ),
    CatalogBook(
        "Moby Dick",
        "Herman Melville",
        "9780142437247",
        "Macera",
        1851,
        "Denizci Ishmael, Kaptan Ahab'ın yönettiği Pequod adlı balina gemisine katılır. Ahab'ın beyaz balina Moby Dick'e duyduğu saplantılı intikam arzusu, gemideki herkesi doğa ve kaderle yıkıcı bir karşılaşmaya sürükler.",
    ),
    CatalogBook(
        "Odysseia",
        "Homeros",
        "9780140268867",
        "Destan",
        -700,
        "Troya Savaşı'nın ardından Odysseus, İthaka'daki evine ve ailesine dönmek için on yıl süren tehlikeli bir yolculuğa çıkar. Canavarlar, büyücüler ve tanrılar karşısında zekâsı ile dayanıklılığı sınanır.",
    ),
    CatalogBook(
        "İlyada",
        "Homeros",
        "9780140275360",
        "Destan",
        -750,
        "Troya Savaşı'nın son döneminde Akhilleus'un öfkesi, onur çatışmaları ve savaşın bedeli anlatılır. Kahramanlık idealiyle insani kayıp yan yana ilerlerken hem ölümlülerin hem tanrıların seçimleri kuşatmanın yönünü değiştirir.",
    ),
    CatalogBook(
        "Dava",
        "Franz Kafka",
        "9780805209990",
        "Klasik",
        1925,
        "Josef K. bir sabah hangi suçla itham edildiğini bilmeden tutuklandığını öğrenir. Görünmez kurallarla işleyen mahkeme sisteminde çıkış aradıkça bürokrasinin mantıksızlığı ve bireyin güçsüzlüğü daha belirgin hâle gelir.",
    ),
    CatalogBook(
        "Çavdar Tarlasında Çocuklar",
        "J. D. Salinger",
        "9780316769488",
        "Roman",
        1951,
        "Okuldan atılan Holden Caulfield birkaç gün boyunca New York sokaklarında dolaşır. Yetişkinlerin ikiyüzlülüğüne duyduğu öfke ile çocukluğun masumiyetini koruma isteği, kırılgan ve dürüst iç sesiyle aktarılır.",
    ),
    CatalogBook(
        "Sineklerin Tanrısı",
        "William Golding",
        "9780399501487",
        "Roman",
        1954,
        "Uçak kazasından kurtulan bir grup çocuk ıssız adada kendi düzenlerini kurmaya çalışır. Başlangıçtaki iş birliği korku ve iktidar mücadelesiyle parçalanırken uygarlığın ince kabuğu hızla ortadan kalkar.",
    ),
    CatalogBook(
        "Mezbaha Beş",
        "Kurt Vonnegut",
        "9780440180296",
        "Bilim Kurgu",
        1969,
        "Billy Pilgrim zamanda kontrolsüzce gidip gelir; savaş esirliğini, Dresden bombardımanını ve uzaylılarla karşılaşmasını tekrar tekrar yaşar. Kara mizah ile bilim kurgu, savaşın anlamsızlığına güçlü bir eleştiri sunar.",
    ),
    CatalogBook(
        "Yüzyıllık Yalnızlık",
        "Gabriel García Márquez",
        "9780060883287",
        "Büyülü Gerçekçilik",
        1967,
        "Buendía ailesinin yedi kuşağı, kurdukları Macondo kasabasında aşkları, savaşları ve tekrar eden yazgılarıyla izlenir. Gerçek ile mucize iç içe geçerken Latin Amerika tarihinin belleği aile hikâyesinde yankılanır.",
    ),
    CatalogBook(
        "Kolera Günlerinde Aşk",
        "Gabriel García Márquez",
        "9780307389732",
        "Roman",
        1985,
        "Florentino Ariza, gençliğinde âşık olduğu Fermina Daza'yı yarım yüzyıldan uzun süre bekler. Zamanın, yaşlanmanın ve değişen hayatların içinden geçen anlatı, aşkın farklı biçimlerini sabırla inceler.",
    ),
    CatalogBook(
        "İmkânsızın Şarkısı",
        "Haruki Murakami",
        "9780375704024",
        "Roman",
        1987,
        "Toru Watanabe bir şarkının tetiklediği anılarla 1960'ların Tokyo'sundaki gençliğine döner. Kayıp, ruhsal kırılganlık ve iki farklı ilişki arasında büyümeye çalışırken sevginin iyileştirici ve yaralayıcı yönlerini keşfeder.",
    ),
    CatalogBook(
        "Kitap Hırsızı",
        "Markus Zusak",
        "9780375842207",
        "Tarihî Roman",
        2005,
        "Nazi Almanyası'nda yaşayan Liesel, çaldığı kitaplar ve kelimeler sayesinde korkuyla baş etmeye çalışır. Koruyucu ailesinin sakladığı Yahudi gençle kurduğu bağ, savaşın ortasında cesaret ve merhametin gücünü gösterir.",
    ),
    CatalogBook(
        "Gülün Adı",
        "Umberto Eco",
        "9780544176560",
        "Polisiye",
        1980,
        "1327 yılında Fransisken rahip William ile çömezi Adso, bir manastırdaki esrarengiz ölümleri araştırır. Yasak kitapların saklandığı labirent kütüphane, inanç, bilgi ve iktidar mücadelesinin merkezine dönüşür.",
    ),
    CatalogBook(
        "Baskerville Tazısı",
        "Arthur Conan Doyle",
        "9780141329390",
        "Polisiye",
        1902,
        "Sherlock Holmes ve Dr. Watson, Baskerville ailesini hedef aldığı söylenen doğaüstü bir tazı efsanesini araştırır. Sisli bozkırdaki ipuçları, batıl korkuların ardında son derece insani bir plan bulunduğunu gösterir.",
    ),
    CatalogBook(
        "Büyük Uyku",
        "Raymond Chandler",
        "9780394758282",
        "Polisiye",
        1939,
        "Özel dedektif Philip Marlowe, zengin Sternwood ailesine yöneltilen şantajı çözmek üzere tutulur. Los Angeles'ın karanlık sokaklarında ilerledikçe kayıp kişiler, suç ağları ve aile sırları birbirine bağlanır.",
    ),
    CatalogBook(
        "Sessiz Hasta",
        "Alex Michaelides",
        "9781250301697",
        "Gerilim",
        2019,
        "Ünlü ressam Alicia Berenson eşini vurduktan sonra tek kelime konuşmaz. Psikoterapist Theo Faber, onun sessizliğini çözmeyi saplantı hâline getirir; araştırması ilerledikçe kendi geçmişi de vakanın içine çekilir.",
    ),
    CatalogBook(
        "Bir Kızın Eğitimi",
        "Tara Westover",
        "9780399590504",
        "Anı",
        2018,
        "Tara Westover okula gönderilmeden, dünyadan yalıtılmış bir aile ortamında büyür. Kendi kendine öğrenerek üniversiteye uzanan yolu, eğitimin yalnız bilgi değil kimlik ve özgürleşme aracı oluşunu anlatır.",
    ),
    CatalogBook(
        "Becoming",
        "Michelle Obama",
        "9781524763138",
        "Biyografi",
        2018,
        "Michelle Obama, Chicago'daki çocukluğundan hukuk kariyerine ve Beyaz Saray yıllarına uzanan yaşamını anlatır. Kamusal sorumluluklar ile aile hayatını dengelerken sesini bulma ve topluma katkı sunma deneyimlerini paylaşır.",
    ),
    CatalogBook(
        "Pürdikkat",
        "Cal Newport",
        "9781455586691",
        "Kişisel Gelişim",
        2016,
        "Dikkat dağıtıcıların yoğun olduğu çalışma dünyasında derin odaklanmanın değerini savunur. Zihinsel kapasiteyi zorlayan kesintisiz çalışma alışkanlıkları geliştirmek için uygulanabilir ilkeler ve günlük düzen önerileri sunar.",
    ),
    CatalogBook(
        "Dört Anlaşma",
        "Don Miguel Ruiz",
        "9781878424310",
        "Kişisel Gelişim",
        1997,
        "Kişisel özgürlük için sözünü özenle kullanmak, hiçbir şeyi kişisel almamak, varsayım yapmamak ve daima elinden gelenin en iyisini yapmak üzerine dört ilke önerir. Bu ilkeleri gündelik yaşama taşımanın yollarını açıklar.",
    ),
)


def ensure_default_catalog(connection) -> int:
    """Insert or enrich starter books without duplicating existing records."""

    inserted = 0
    for book in DEFAULT_CATALOG:
        existing = connection.execute(
            """
            SELECT id FROM books
            WHERE isbn = ? COLLATE NOCASE
               OR (title = ? COLLATE NOCASE AND author = ? COLLATE NOCASE)
            ORDER BY CASE WHEN isbn = ? COLLATE NOCASE THEN 0 ELSE 1 END
            LIMIT 1
            """,
            (book.isbn, book.title, book.author, book.isbn),
        ).fetchone()
        if existing:
            isbn_owner = connection.execute(
                "SELECT id FROM books WHERE isbn = ? COLLATE NOCASE", (book.isbn,)
            ).fetchone()
            isbn_value = book.isbn if not isbn_owner or isbn_owner[0] == existing[0] else None
            connection.execute(
                """
                UPDATE books
                SET isbn = COALESCE(?, isbn), category = ?, published_year = ?,
                    description = ?, cover_image_url = ?
                WHERE id = ?
                """,
                (isbn_value, book.category, book.year, book.summary, book.cover_url, existing[0]),
            )
            continue

        connection.execute(
            """
            INSERT INTO books
                (title, author, isbn, category, published_year, description,
                 cover_image_url, total_copies, available_copies, is_active)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
            """,
            (
                book.title,
                book.author,
                book.isbn,
                book.category,
                book.year,
                book.summary,
                book.cover_url,
                book.copies,
                book.copies,
            ),
        )
        inserted += 1
    return inserted
